services:

  model-service:
    build: ./model_service
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      model-service:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always